### ISSUE TITLE
Login on test.c4dt.org

### ISSUE THREAD

**Issue by ineiti** [c4dt/omniledger#109]
- [x] Find out the correct domain of the test-instance of c4dt (check with David) and set up the login-plugin there
- [x] Create 2 pages in WordPress that are protected and only visible with the login
  - [x] Have pages in "members only"
  - [x] when clicking on "members only", go to login page
  - [x] when login page successful, go to "members only"
- [ ] Test it with somebody from SwissRe and Elca
  - [x] tested locally with 53 & 443 opened
- [ ] Make sure PaperBoy knows about the plugin and won't delete it

**Comment by tharvik** [comment]
Timeout for SwissRe and PaperBoy.
