### ISSUE TITLE
Login-tests

### ISSUE THREAD

**Issue by ineiti** [c4dt/omniledger#112]
Write a test-framework that can do 100 logins/h for one week

**Comment by tharvik** [comment]
"login" from where to where? We already have a (small) test fw, which is testing `serviceValidate` from a HTTP POV, with a locally generated ByzCoin.

The best would be to test from client browser clicking "Login with SSO" to client browser accessing the service, something using Selenium, that could easily test the whole integration if running directly on the infrastructure.

**Comment by tharvik** [comment]
It can be linked to #111

**Comment by ineiti** [comment]
#111 is a regular status-page
#112 is a special "make JP and Olivier confident about our solution" issue
