### ISSUE TITLE
Login on c4dt.org

### ISSUE THREAD

**Issue by ineiti** [c4dt/omniledger#113]
- [ ] Install the plugin on the _real_ c4dt.org website
  - [x] unable to write to server's FS, unable to rm dangling Authorizer, see with @ineiti 
- [x] Write instructions for David so he can add protected pages
- [x] Write instructions for partners on how to use the login-service - as little as necessary in external documents, as much as possible directly in the webpages

**Comment by tharvik** [comment]
"protected websites", WDYM? Other valid services such as `matrix.c4dt.org`?

**Comment by ineiti** [comment]
s/websites/webpages/

**Comment by tharvik** [comment]
> Write instructions for partners on how to use the login-service - as little as necessary in external documents, as much as possible directly in the webpages

Targeting who?
 * commercials: then, what to explain: how is it working (ident on chain, proof of login) or smth else?
 * devs: won't these be more interrested in having it directly in `omniledger/webapp/cas`?

**Comment by ineiti** [comment]
I think for the documentation, the current state of login is quite good and doesn't need to be changed a lot. Two possible low hanging fruits:
- when waiting for authorization in the demo...cas login, there should be a spinner, to show that something is happening. Or show the transaction-window, if the transaction is already done at that point. Also use the same formatting as for the other pages of the omniledger-demo with respect to the border and centering.
- no 404's anywhere, even during failed logins

**Comment by tharvik** [comment]
* styles done in #134 
* 404, if you find some other than `/logout`, tell me
