### ISSUE TITLE
ShowActivity sometimes fails

### ISSUE THREAD

**Issue by ineiti** [c4dt/omniledger#143]
Under some circumstances (yet to be found out), `showActivity` fails with an error "insecure something something".

Most probable cause: one of the non-https conodes is contacted and the browser refuses to use it.

Here a screenshot of when things go bad:

![Error_SingleSignOn](https://user-images.githubusercontent.com/1545067/65949968-71821800-e43d-11e9-8748-0c0464ed331f.PNG)

**Comment by tharvik** [comment]
Google Chrome
```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws:<URL>/Skipchain/GetUpdateChain'. This request has been blocked; this endpoint must be available over WSS
--
SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS
```

**Comment by ineiti** [comment]
And why does the connector use sometimes insecure nodes?

**Comment by tharvik** [comment]
Some Roster don't contain the `Url` field, which then default to building one with proto `ws:`. Fix is in https://github.com/c4dt/cothority/pull/3.

**Comment by tharvik** [comment]
Nope, it's was indeed fixed.
