### ISSUE TITLE
OmniLedger Explorer

### ISSUE THREAD

**Issue by ineiti** [c4dt/omniledger#216]
There is a simple explorer in omniledger, but it misses a lot of UI niceness:
- better UI with
  - field to enter any ID (block or instance)
  - easy navigation from one element to the next
- merge with the block-explorer in omniledger

**Comment by nkcr** [comment]
There are actually two semester projects going on that aim to tackle those points, could be interesting for you to join one of the meeting if you have ideas to bring :) 
In the meantime, there is https://wookiee.ch/columbus/ that allows you to fetch a particular block.

**Comment by ineiti** [comment]
Good idea - I think we'll meet next Tuesday, no?

**Comment by nkcr** [comment]
Yes, that will be the perfect occasion.

**Comment by ineiti** [comment]
Here you go - 2 days late for the anniversary: https://github.com/dedis/columbus-united

**Comment by nkcr** [comment]
That's so cool, this is the official "Linus Approved", and that means a lot! 😃
Thank you @foocil, @Anthony-Iozzia, @LucasTrg, and @sophiartl for your work.
