### ISSUE TITLE
use NativeScript 6, with webpack magic

### ISSUE THREAD

**Issue by tharvik** [c4dt/omniledger#227]
Since dedis/cothority#2196, `url-parse` is removed from cothority. It was a trick to make it work across nodejs, browsers and nativescript. As webpack seems pretty powerful for handling theses different environements, using the latest version will hopefully make it work.

When done, one would have to check that browser's `URL` can be used in the code and still be working in the mobile.

**Comment by ineiti** [comment]
I think that one didn't work as expected - url-pars is back...
