### ISSUE TITLE
drynx-cas

### ISSUE THREAD

**Issue by ineiti** [c4dt/omniledger#246]
Today I tried the following link, https://demo.c4dt.org/drynx/stackblitz

But it failed with a 'no such service' error in the javascript-console. On the UI, only the following is visible:
```
An external app coming from demo.c4dt.org/drynx/stackblitz asked to log you in.

We are checking if you have access...
```

On the javascript console I get:

```
main.c8c5deb7b38c77d64d85.js:1 ERROR Error: Uncaught (in promise): Error: no such service found: http://demo.c4dt.org/drynx/stackblitz
Error: no such service found: http://demo.c4dt.org/drynx/stackblitz
```

**Comment by tharvik** [comment]
> 1. https://demo.c4dt.org/drynx/stackblitz
> failed with a 'no such service' error in the javascript-console.

Added such service in cas.conf

> 2. https://demo.c4dt.org/drynx
> failed with a URL that had some `?...` appended to it

It shouldn't fail, the ticket is gave back by CAS and is used once until the login cookie is created.

> Currently I cannot reproduce it, as I'm logged in - what is the best way to log out from apache-cas?

You can delete the `MOD_AUTH_CAS` cookie from your browser.

**Comment by tharvik** [comment]
'no such service' is followed here: https://github.com/c4dt/omniledger/issues/237

**Comment by ineiti** [comment]
I only had 2. once, and couldn't reproduce it, even after deleting the cookie.
