### ISSUE TITLE
deleted actions/groups are not really deleted

### ISSUE THREAD

**Issue by tharvik** [c4dt/omniledger#26]
In contacts
- create an action/group
- copy its id
- delete the action/group
- add the action's id
- it is added as an existing action/group but shouldn't as it is deleted

**Comment by ineiti** [comment]
Not sure this is a bug. There should perhaps be two buttons:
- `forget` - removes the link in the list from the user
- `destroy` - calls `Delete` on ByzCoin

The `destroy` is somewhat dangerous, as this darc might be in use somewhere else. So in fact I prefer very much the current system where the darcs are not actually deleted from ByzCoin.

**Comment by tharvik** [comment]
I see; hum, yeah, IMO, having two buttons can be confusing to the user: what do you think of a rename from "Delete" (implying the unreversible vanishing of an object)  to "Remove" (implying crossing it out of a list but the object is still existing afterward)?

**Comment by ineiti** [comment]
More thoughts:
- `Forget`
- `Unlink`
- `Unlike`
- `Strike out`

**Comment by tharvik** [comment]
If we can find coherence between Add/Remove, that would even nicer; so that would roughly give

| ++ | -- |
| --- | --- |
| Add | Remove |
| Remember | Forget |
| Link | Unlink |
| Like | Unlike |
| Write in | Strike out |

I'm more for Add/Remove and Link/Unlink, that seems clearer

**Comment by ineiti** [comment]
`s/Remember/Learn/`

But I think that your two pairs make sense. Go for `Add/Remove`, `Link/Unlink` then.
