### ISSUE TITLE
Mobile Bitrotting

### ISSUE THREAD

**Issue by ineiti** [c4dt/omniledger#275]
The mobile app doesn't compile anymore. It complains with an `XMLHttpRequest not defined`, which is strange, as it's the same version that _did_ compile at the beginning of this year.

Even worse, when I started on my computer on the 15th of September, it _did_ compile! But after an `npm ci` it always failed. So far I tried:
- basic stuff
  - `make clean` 
  - fresh checkout
- putting all versions to the numbers given in `mobile/README.md`
- using the first 5 matches from Google, but it fails because I cannot set the global `XMLHttpRequest`
- going back in time and using the first commit

I'm currently trying to start 'from scratch' with nativescript 7 (`master` uses nativescript 5), but it fails somewhere in importing @dedis/kyber...

**Comment by calctopian** [comment]
Just a small suggestion: after `npm ci`, have you run `make apply-patches`? 
Reasoning:
1. `make apply-patches` modifies `node_modules/nativescript-nodeify/nodeify.js` and `node_modules/nativescript-nodeify/patch-npm-packages.js`
2. `npm ci` removes `node_modules/`
3. After `npm ci`, you have lost the changes previously applied by `make apply-patches`, thus you must always execute `make apply-patches` after `npm ci`

**Comment by tharvik** [comment]
> I'm currently trying to start 'from scratch' with nativescript 7 (`master` uses nativescript 5), but it fails somewhere in importing @dedis/kyber...

What's the error with @dedis/kyber?

**Comment by ineiti** [comment]
> Just a small suggestion: after `npm ci`, have you run `make apply-patches`?

Thanks! Yes, I `RTFM` and used `make` to get a compiled version again.
