### ISSUE TITLE
Performance evaluation of View Change

### ISSUE THREAD

**Issue by Raycoms** [c4dt/omniledger#281]
Hello,

I was wondering if this implementation includes the rotating view change algorithm (querying the other leave processes in case of internal node failure) as demonstrated in the paper?

Is it possible to run the chain to evaluate the performance of this using this repository code?

**Comment by ineiti** [comment]
Yes. It currently works like this;
- A client sends his transaction to one or more nodes
- The nodes forward the transaction to the leader
- If the leader doesn't accept the transaction, the nodes forward the transaction to all other nodes
- If 2/3 of the nodes agree that the leader doesn't accept the transaction, they send a request to the next leader of the node list
- After an exponential timeout, the index is increased, until one of the nodes accepts to be the leader

The tests of the viewchange are here: https://github.com/dedis/cothority/tree/master/byzcoin/viewchange
End-to-end tests of the viewchange are here: https://github.com/dedis/cothority/blob/master/byzcoin/viewchange_test.go
A script that sets up nodes and then kills a node to verify the viewchange is happening, is here: https://github.com/c4dt/byzcoin/blob/master/update_test.sh

Please also be aware that the `c4dt/omniledger` repo is merely the client-side library of the `c4dt/byzcoin` code that describes the nodes.

**Comment by Raycoms** [comment]
I have a stronger focus on the quorum collection part. In the paper it was described that if the leader is not able to collect a quorum through the tree, it will query additional leave processes until it was able to collect a full quorum.

**Comment by ineiti** [comment]
That part is done through a sub-leader change: if the current sub-leader cannot get a quorum, the leader choses the next sub-leader to try to get another quorum.

**Comment by Raycoms** [comment]
okay great, I was worrying that it wasn't fully implemented yet.
