### ISSUE TITLE
Regarding Algorithm

### ISSUE THREAD

**Issue by rsshevkar** [c4dt/omniledger#282]
Hello Inventors,
I am a research student and interested in the sharding algorithm used for omniledger.

**Comment by ineiti** [comment]
Thanks for your interest. We currently don't use sharding in that implementation. There is a long-due PR that would introduce sharding here: https://www.epfl.ch/labs/dedis/wp-content/uploads/2020/01/report-2018_2-quangminh-omniledger_sharding.pdf - but we never got around to finish it.
