### ISSUE TITLE
Update the readme with the makefile instructions

### ISSUE THREAD

**Issue by LucasTrg** [c4dt/omniledger#285]

**Comment by ineiti** [comment]
As I did some work on the Makefile, just try a `git clone; make` and see if it works.

**Comment by ineiti** [comment]
Then just add a small text, like
```
# Run it locally

cd webapp
make

and then open localhost:8000
```

**Comment by LucasTrg** [comment]
I just tested the new makefile and it works great, even without angular-cli and other dependencies that are generally globally installed. I'll edit the readme accordingly (the port is actually 4200 not 8000 if I'm not mistaken)

**Comment by LucasTrg** [comment]
Should I also edit webapp/README.md accordingly as well? It goes into much more detail in the building process using docker... is it now equivalent to use the makefile? Or should the "advanced" instructions stay?

**Comment by ineiti** [comment]
With regard to `webapp/README.md`, it should hold the following information - don't hesitate to ask for more info if needed:
1. the webapp can either connect to the test-network of DEDIS by running `make serve`
2. it can also use a local network, which is described by using `make docker`, but then the `src/assets/config.local.toml` needs to be copied to `src/assets/config.toml`

**Comment by LucasTrg** [comment]
I've been trying to run the nodes using ```make docker``` in the conode folder, but I've been running into some issues. Unfortunately, all of the go dependencies have to be downloaded manually (including some packages), and I did not find a way to get go 1.16, the archive page on the golang website only allows to download 1.16.3 which prevents me from building the docker image : 
```# runtime/cgo
compile: version "go1.16" does not match go tool version "go1.16.3"
```
Therefore I can't be 100% sure the instructions will work fine. Notheless, I'll push in a few minutes my changes to the readme

**Comment by LucasTrg** [comment]
I just realized I probably needed to use the cothority makefile instead of the conode one...

**Comment by ineiti** [comment]
Closing because omniledger is now unsupported
