### ISSUE TITLE
npm build --prod fails

### ISSUE THREAD

**Issue by ineiti** [c4dt/omniledger#334]
When building the webapp with `npm build --prod`, the resulting scripts do nothing: when loading the `index.html` there is no output in the console.

Currently only `npm build` works. One could probably use `git bisect`, or do it manually, to find the commit that makes it fail.

I guess the following might be the culprit, as it updates to the latest cothority:

https://github.com/c4dt/omniledger/commit/1f694e281d410309eb78818efbf02b6b05d53853

**Comment by tharvik** [comment]
So I digged a bit more. It seems that the `ng build --prod` uses [@angular-devkit/build-optimizer](https://www.npmjs.com/package/@angular-devkit/build-optimizer), which fails to generate a working page. Disabling it in angular.json fixes that (so we don't disable all optimization: terser & aot are kept). Adding it to #333
